# Goop compiler configuration
# See docs/design/05-modules-and-packages.md for details.

module_root = "github.com/Macho0x/Goop"

[check]
exhaust_redundant = "warn"
exhaust_missing = "error"
effect_inference = true
concurrent = "error"
refinement_unproven = "warn"
deadlock = "warn"
discarded_result = "warn"
smt = false

[mappings]
"std.io"      = "github.com/Macho0x/Goop/std/io"
"std.list"    = "github.com/Macho0x/Goop/std/list"
"std.map"     = "github.com/Macho0x/Goop/std/map"
"std.array"   = "github.com/Macho0x/Goop/std/array"
"std.option"  = "github.com/Macho0x/Goop/std/option"
"std.result"  = "github.com/Macho0x/Goop/std/result"
"std.decimal" = "github.com/Macho0x/Goop/std/decimal"
"std.string"  = "github.com/Macho0x/Goop/std/string"
"std.chan"    = "github.com/Macho0x/Goop/std/channel"
"std.ref"     = "github.com/Macho0x/Goop/std/ref"
