package main

import (
	"os"
	"strings"
	"testing"

	"goop.dev/compiler/internal/gosiggen"
)

func TestGetGoSigUsage(t *testing.T) {
	if runGetGoSig(nil) == 0 {
		t.Fatal("expected failure with no args")
	}
}

func TestGetGoSigWritesCache(t *testing.T) {
	home := t.TempDir()
	t.Setenv("GOOP_HOME", home)

	code := runGetGoSig([]string{"errors"})
	if code != 0 {
		t.Fatalf("get-go-sig errors: exit %d", code)
	}
	want := gosiggen.CachePath(home, "errors")
	data, err := os.ReadFile(want)
	if err != nil {
		t.Fatalf("expected cache file %s: %v", want, err)
	}
	if !strings.Contains(string(data), "Generated by goop") {
		t.Fatalf("unexpected content:\n%s", data)
	}
}
